# v1.2.110 _config.yml

title: Snooey
url:  https://snooey.com
baseurl: /
separator: " | "
locale: en
timezone: Australia/Brisbane
copyright: Copyright (c) 2018-2022 Shane Hoey

# VNEXT TODO - Jekyll-seo-tag
# tagline: "Snooey Jekyll Theme"
# description:
# url: https://snooey.com
# author:
# twitter:
#    twitter: summary
#    username: shanehoey
# social:
# webmaster_verifications:
#    google:
#    bing:

exclude:
    - LICENSE
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - SECURITY.md
    - _dev/
#    - _dev/_includes/
#    - _dev/_layouts/
#    - _dev/dataset/
#    - _dev/pages/
#    - _dev/schema/
    
plugins_dir: _plugins
plugins:
    - jekyll-remote-theme
    - jekyll-sitemap
    - jekyll-optional-front-matter
    - jekyll-admin
    - jekyll-redirect-from

remote_theme: shanehoey/snooey

include:
    - _pages
    - _redirects

collections_dir: collections

collections:
    docs:
        output: true
        permalink: /documents/:path/
    tools:
        output: true
        permalink: /:collection/:path/
    videos:
        output: true
        permalink: /:collection/:path/
    automation:
        output: true
        permalink: /:collection/:path/

defaults:
    - scope:
        path: ""
      values:
        title:
        subtitle:
        excerpt:
        description:
        icon: bi bi-file-earmark
        button:
          icon: bi bi-link
          text: read more
          url:
        image: 
          header: https://placeimg.com/2560/640/tech
          vertical: https://placeimg.com/800×1200/tech
          horizontal: https://placeimg.com/1200/800/tech
        author:     Shane Hoey
        debug:      true      # true/false - should be false for production
        layout:     default   # default/page/paginate/post/video
        navbar:     true      # true/false
        breadcrumb: true      # true/false
        carousel:   false     # true/false
        footer:     true      # true/false
        brand:      brand1    # sets the default branding for page
        theme:      theme1    # sets the default css classes(theme[1..5])
        schema:     light     # sets the schema for the page (dark,light,image/custom)
        dataset:    dataset1  # sets the default dataset for the page (dataset[1..5]/custom)
    - scope:
        path:       ""
        type:       pages
      values:
        layout:     page
    - scope:
        path:       ""
        type:       posts
      values:
        layout:     post
        permalink:  /blogs/:slug
    - scope:
        path:       ""
        type:       tools
      values:
        layout:     tools
    - scope:
        path:       ""
        type:       docs
      values:
        layout:     docs
    - scope:
        path:       ""
        type:       videos
      values:
        layout:     videos
    - scope:
        path:       ""
        type:       automation
      values:
        layout:     automation
    - scope:        # remove from production sites, only to show content examples
        path:       pages/theme/
        type:       pages
      values:
        debug:      true
        layout:     default
        navbar:     false
        breadcrumb: false 
        carousel:   false
        footer:     false
        permalink:  /theme/:slug
        