# v1.00 _config.yml

title: Snooey
url:  https://snooey.com
baseurl: /
separator: " | "
locale: en
timezone: Australia/Brisbane
copyright: Copyright (c) 2018-2020 Shane Hoey

# Future Use - Jekyll-seo-tag
# tagline: "Snooey Jekyll Theme"
# description:
# url: https://snooey.com
# author:
# twitter:
#    twitter: summary
#    username: shanehoey
# social:
# webmaster_verifications:
#    google:
#    bing:

exclude:
    - LICENSE
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock

plugins_dir: _plugins
plugins:
    - jekyll-remote-theme
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-spaceship
    - jekyll-toc

remote_theme: shanehoey/snooey

include:
    - _pages
    - _redirects

collections_dir: collections

collections:
    code:
        output: true
        permalink: /:collection/:path/
    docs:
        output: true
        permalink: /documents/:path/
    snippets:
        output: true
        permalink: /:collection/:path/
    tldr:
        output: true
        permalink: /:collection/:path/
    tools:
        output: true
        permalink: /:collection/:path/
    videos:
        output: true
        permalink: /:collection/:path/
    automate:
        output: true
        permalink: /:collection/:path/

defaults:
    - scope:
          path: ""
      values:
          title:
          subtitle:
          excerpt:
          description:
          author: Shane Hoey
          icon: fas fa-rocket
          navbar:    true
          breadcrumb: true
          carousel:  false
          footer:    true
          brand:     brand1
          theme:     theme1
          scheme:    default
          image:
              default: https://source.unsplash.com/random/800x600
              horizontal: https://source.unsplash.com/random/750x400
              vertical: https://source.unsplash.com/random/400x750
              square: https://source.unsplash.com/random/300x300
              random: https://source.unsplash.com/random/750x400
              background: https://source.unsplash.com/random/2400x1800
              profile: https://source.unsplash.com/random/300x450
    - scope:
          path: ""
          type: pages
      values:
          layout:  page
          brand:   brand1
          theme:   theme1
          scheme:  default  
    - scope:
          path: ""
          type: posts
      values:
          layout:    post
          brand:     brand4
          theme:     theme1
          scheme:    default
          permalink: /blogs/:slug/
    - scope:
          path: ""
          type: code
      values:
          layout: code
          brand:   brand3
          theme:   theme1
          scheme:  default
    - scope:
          path: ""
          type: docs
      values:
          layout:  docs
          brand:   brand2
          theme:   theme1
          scheme:  default
    - scope:
          path:  ""
          type:  tools
      values:
          layout: tools
          brand:  brand3
          theme:  theme1
          scheme: default
    - scope:
          path: ""
          type: snippets
      values:
          layout: snippets
          brand: brand3
          theme: theme1
          scheme: default
    - scope:
          path: ""
          type: tldr
      values:
          layout: tldr
          brand: brand2
          theme: theme1
          scheme: default
    - scope:
          path: ""
          type: videos
      values:
          layout: videos
          brand: brand2
          theme: theme1
          scheme: default
    - scope:
          path:  ""
          type:  automate
      values:
          layout: automate
          brand: brand3
          theme: theme1
          scheme: default
          