# v1.2.121 _config.yml

title: Snooey
url:  https://snooey.com
baseurl: /
separator: " | "
locale: en
timezone: Australia/Brisbane
copyright: Copyright (c) 2018-2022 Shane Hoey

# VNEXT TODO - Jekyll-seo-tag
# tagline: "Snooey Jekyll Theme"
# description:
# url: https://snooey.com
# author:
# twitter:
#    twitter: summary
#    username: shanehoey
# social:
# webmaster_verifications:
#    google:
#    bing:

exclude:
    - LICENSE
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - SECURITY.md
    - _dev/

plugins_dir: _plugins
plugins:
    - jekyll-remote-theme
    - jekyll-sitemap
    - jekyll-optional-front-matter
    - jekyll-admin
    - jekyll-redirect-from
    - jekyll-minifier
 
jekyll-minifier:
    compress_javascript: false

excerpt_separator: <!--more-->

remote_theme: shanehoey/snooey

include:
    - _pages
    - _redirects

collections_dir: collections

collections:
    code:
        output: true
        permalink: /:collection/:path/
    docs:
        output: true
        permalink: /documents/:path/
    tools:
        output: true
        permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
    values:
      title:
      subtitle:
      heading:
      description:
      guid:
      authorid: shanehoey
      link: &link
        icon: bi bi-link
        text: read more
        url:
      assets: &assets
        icon:       bi bi-file-earmark
        header:     https://placeimg.com/2560/640/tech
        square:     https://placeimg.com/300/300/tech
        vertical:   https://placeimg.com/800×1200/tech
        horizontal: https://placeimg.com/1200/800/tech
        teaser:     https://placeimg.com/700/394/tech
        background: https://placeimg.com/1920/1080/tech
      categories: []
      layout:     default   # default/page/paginate/post/video
      navbar:     true      # true/false
      breadcrumb: true      # true/false
      carousel:   false     # true/false
      footer:     true      # true/false
      brand:      brand1    # sets the default branding for page
      theme:      theme1    # sets the default css classes(theme[1..5])
      schema:     light     # sets the schema for the page (dark,light,image/custom)
  - scope:
      path:       ""
      type:       pages
    values:
      layout:     page
      link:
        <<: *link
      assets:
        <<: *assets
  - scope:
      path:       ""
      type:       posts
    values:
      layout:     post
      permalink:  /posts/:slug
      link:
        <<: *link
      assets:
        <<: *assets

  - scope:
      path:       ""
      type:       code
    values:
      layout:     code
      categories: ["code"]
      link:
        <<: *link
        icon: bi bi-file-code
      assets:
        <<: *assets
  - scope:
      path:       "collections/_code/github/"
      type:       code
    values:
      layout:     github
      categories: ["github"]
      link:
        <<: *link
        icon: bi bi-file-code
      assets:
        <<: *assets
      
  - scope:
      path:       "collections/_code/gist/"
      type:       code
    values:
      layout:     gist
      link:
        <<: *link
        icon: bi bi-file-code
      assets:
        <<: *assets
      categories: ["gist"]  
  - scope:
      path:       ""
      type:       docs
    values:
      layout:     docs
      link:
        <<: *link
        icon: bi bi-file-text
      assets:
        <<: *assets
      categories: ["docs"]
  - scope:
      path:       "collections/_docs/document/"
      type:       docs
    values:
      categories: ["document"]
      layout:     docs
      link:
        <<: *link
        icon: bi bi-file-text
      assets:
        <<: *assets
  - scope:
      path:       "collections/_docs/videos/"
      type:       docs
    values:
      categories: ["video"]
      layout:     videos
      link:
        <<: *link
        icon: bi bi-file-play
      assets:
        <<: *assets
  - scope:
      path:       ""
      type:       tools
    values:
      categories: ["tools"]
      layout:     tools
      link:
        <<: *link
        icon: bi bi-tools
      assets:
        <<: *assets
  - scope:        # remove from production sites, only to show content examples
      path:       pages/theme/
      type:       pages
    values:
      layout:     page
      breadcrumb: false 
      permalink:  /theme/:slug
