# v1.2.121 _config.yml

title: Snooey
url: https://snooey.com
baseurl: /
separator: " | "
locale: en
timezone: Australia/Brisbane
copyright: Copyright (c) 2018-2022 Shane Hoey

# VNEXT TODO - Jekyll-seo-tag
# tagline: "Snooey Jekyll Theme"
# description:
# url: https://snooey.com
# author:
# twitter:
#    twitter: summary
#    username: shanehoey
# social:
# webmaster_verifications:
#    google:
#    bing:

exclude:
    - LICENSE
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - SECURITY.md
    - _dev/
    - docker-compose.dev.yml 
    - docker-compose.prod.yml
    - structure.md

plugins_dir: _plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-admin
  - jekyll-redirect-from
  - jekyll-minifier

# BUG: issue when js compressed
jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  compress_css: true
  compress_javascript: false 

excerpt_separator: <!--more-->

remote_theme: shanehoey/snooey

include:
  - _pages
  - _redirects
  - favicon.ico

collections_dir: collections

collections:
  brand1:
      output: true
      permalink: /:collection/:path/
  brand2:
      output: true
      permalink: /:collection/:path/
  brand3:
      output: true
      permalink: /:collection/:path/
  brand4:
      output: true
      permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
    values:
      title:
      subtitle:
      heading:
      description:
      guid:  00000000-0000-0000-0000-000000000000
      author: shanehoey
      link: &link
        icon: bi bi-link
        text: read more
        url:
      assets: &assets
        icon: bi bi-file-earmark
        background: "/assets/images/brand0/background.jpg"
        horizontal: "/assets/images/brand0/horizontal.jpg"
        vertical: "/assets/images/brand0/vertical.jpg"
        square: "/assets/images/brand0/square.jpg"
        profile: "/assets/images/brand0/profile.jpg"
        header: "/assets/images/brand0/header.jpg"
        teaser: "/assets/images/brand0/teaser.jpg"
      categories: []
      layout: brand0   # default/page/paginate/post/video
      navbar: true      # true/false
      breadcrumb: true      # true/false
      carousel: false     # true/false
      footer: true      # true/false
      brand: brand0    # sets the default branding for page (brand0)
      theme: theme0    # sets the default css classes (theme[1..5]])

  - scope:
      path: ""
      type: pages
    values:
      layout: page
      link:
        <<: *link
      assets:
        <<: *assets
  
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:slug
      link:
        <<: *link
      assets:
        <<: *assets

  - scope:
      path: "/brand1/*"
      type: brand1
    values:
      layout: brand1
      brand: brand1
      theme: theme1
      categories: ["brand1"]
      link:
        <<: *link
      assets:
        <<: *assets
        icon: bi bi-file-text
  
  - scope:
      path: ""
      type: brand2
    values:
      layout: brand2
      brand: brand2
      theme: theme2
      link:
        <<: *link
      assets:
        <<: *assets
        icon: bi bi-file-text
      categories: ["brand2"]
  
  - scope:
      path: ""
      type: brand3
    values:
      categories: ["brand3"]
      layout: brand3
      brand: brand3
      theme: theme3
      link:
        <<: *link
      assets:
        <<: *assets
        icon: bi bi-file-text
  
  - scope:
      path: ""
      type: brand4
    values:
      categories: ["brand4"]
      layout: brand4
      brand: brand4
      theme: theme4
      link:
        <<: *link
      assets:
        <<: *assets
        icon: bi bi-file-text
 