# v1.00 _config.yml

title: Snooey
url:  https://snooey.com
baseurl: /
separator: " | "
locale: en
timezone: Australia/Brisbane
copyright: Copyright (c) 2018-2022 Shane Hoey

# Future Use - Jekyll-seo-tag
# tagline: "Snooey Jekyll Theme"
# description:
# url: https://snooey.com
# author:
# twitter:
#    twitter: summary
#    username: shanehoey
# social:
# webmaster_verifications:
#    google:
#    bing:

exclude:
    - LICENSE
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock

plugins_dir: _plugins
plugins:
    - jekyll-remote-theme
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-spaceship
    - jekyll-toc

remote_theme: shanehoey/snooey

include:
    - _pages
    - _redirects

collections_dir: collections

collections:
    code:
        output: true
        permalink: /:collection/:path/
    docs:
        output: true
        permalink: /documents/:path/
    videos:
        output: true
        permalink: /:collection/:path/

defaults:
    - scope:
          path: ""
      values:
          title:
          subtitle:
          excerpt:
          description:
          author:     Shane Hoey
          icon:       fas fa-rocket
          debug:      true      # true/false - should be false for production
          layout:     default   # default/page/paginate/post/video
          navbar:     true      # true/false
          breadcrumb: true      # true/false
          carousel:   true      # true/false
          footer:     true      # true/false
          content:    brand1    # sets the Default for the page or include
          theme:      theme1    # sets the default css classes
          schema:     dark      # dark,light,image
    - scope:
          path: ""
          type: pages
      values:
          layout:  page
    - scope:
          path: ""
          type: posts
      values:
          layout:    post
          permalink: /blogs/:slug/
    - scope:
          path: ""
          type: videos
      values:
          layout: videos
