# v1.2.135 _config.docker.yml

url:  "http://localhost"

liquid:  #https://jekyllrb.com/docs/configuration/liquid/
  error_mode: warn
  strict_variables: false
  strict_filters: false

remote_theme: shanehoey/snooey@dev