version: '3'

services:
    development:
        image: jekyll/jekyll:latest
        command: jekyll serve --watch --force_polling --incremental --drafts --future --unpublished
        ports:
            - 80:4000
        volumes:
            - .:/srv/jekyll
        environment:
            - NODE_ENV=development
            - JEKYLL_ENV=development
   